# Generated by Django 2.2 on 2019-10-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalUrl', models.CharField(max_length=300, unique=True)),
                ('shortUrl', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'default_permissions': {'delete'},
            },
        ),
    ]
